nshipping/apps/ingreso/urls.py
from django.conf.urls import url, patterns, include
from rest_framework import routers
from . import views
from .viewsets import ClientViewSet, ClienteViewSet
from .models import Client

router = routers.SimpleRouter()
router.register(r'clientes',ClienteViewSet)
router.register(r'cliente', ClientViewSet,base_name = Client)
urlpatterns = [
    url(r'^api/',include(router.urls)),
    url(
        r'^panel/nota-ingreso/$',
        views.DepositSlipView.as_view(),
        name='nota-ingreso'
    ),
    url(
        r'^panel/envio/(?P<pk>\d+)/imprimir/$',
        views.EnvioPrintView.as_view(),
        name='print-envio'
    ),
    url(
        r'^panel/imprimir/nota-ingreso/(?P<pk>\d+)/$',
        views.ReportNotaView.as_view(),
        name='print-nota-ingreso'
    ),
    url(
        r'^panel/imprimir/guia/(?P<pk>\d+)/$',
        views.ReportGuiaView.as_view(),
        name='print-guia'
    ),
    url(
        r'^panel/imprimir/comprobante/(?P<pk>\d+)/$',
        views.ReportComprobanteView.as_view(),
        name='print-comprobante'
    ),
    url(
        r'^panel/entregar-envio/$',
        views.DeliverView.as_view(),
        name='lista_envio'
    ),
    url(
        r'^panel/entregar-envio/(?P<pk>\d+)/$',
        views.DetailDeliverView.as_view(),
        name='detalle_envio'
    ),
    # url para manteniminetos de sucursales
    url(
        r'^sucursales/listar/$',
        views.ListBranchView.as_view(),
        name='listar-branch'
    ),
    url(
        r'^sucursales/add/$',
        views.RegisterBranchView.as_view(),
        name='agregar-branch'
    ),
    url(
        r'^sucursales/update/(?P<pk>\d+)$',
        views.UpdateBranchView.as_view(),
        name='actualizar-branch'
    ),
    url(
        r'^sucursales/detail/(?P<pk>\d+)$',
        views.DetailBranchView.as_view(),
        name='detalle-branch'
    ),
    url(
        r'^sucursales/delete/(?P<pk>\d+)$',
        views.DeleteBranchView.as_view(),
        name='eliminar-branch'
    ),
]

nshipping/apps/manifiesto/urls.py
from django.conf.urls import url, patterns, include
from rest_framework import routers
from django.conf.urls import url
from .models import Manifest
from .viewsets import ManifestViewSet
from . import views


router = routers.SimpleRouter()
router.register(r'manifiesto', ManifestViewSet,base_name = Manifest)

urlpatterns = [
    url(r'^api/',include(router.urls)),
    url(
        r'^manifiesto/car/listar/$',
        views.ListCarView.as_view(),
        name='listar-carro'
    ),
    url(
        r'^manifiesto/car/add/$',
        views.RegisterCarView.as_view(),
        name='agregar-carro'
    ),
    url(
        r'^manifiesto/car/update/(?P<pk>\d+)/$',
        views.UpdateCarView.as_view(),
        name='actualizar-carro'
    ),
    url(
        r'^manifiesto/car/delete/(?P<pk>\d+)/$',
        views.DeleteCarView.as_view(),
        name='eliminar-carro'
    ),
    url(
        r'^manifiesto/car/detail/(?P<pk>\d+)/$',
        views.DetailCarView.as_view(),
        name='visualizar-carro'
    ),
    # url conductor
    url(
        r'^manifiesto/driver/listar/$',
        views.ListDriverView.as_view(),
        name='listar-conductor'
    ),
    url(
        r'^manifiesto/driver/add/$',
        views.RegisterDriverView.as_view(),
        name='agregar-conductor'
    ),
    url(
        r'^manifiesto/driver/update/(?P<pk>\d+)/$',
        views.UpdateDriverView.as_view(),
        name='actualizar-conductor'
    ),
    url(
        r'^manifiesto/driver/detail/(?P<pk>\d+)/$',
        views.DetailDriverView.as_view(),
        name='visualizar-conductor'
    ),
    url(
        r'^manifiesto/driver/delete/(?P<pk>\d+)/$',
        views.DeleteDriverView.as_view(),
        name='eliminar-conductor'
    ),
    # url para mantenimietno manifiesto
    url(
        r'^manifiesto/listar/$',
        views.ManifestList.as_view(),
        name='listar-manifiesto'
    ),
    url(
        r'^manifiesto/crear-manifiesto/$',
        views.ManifestView.as_view(),
        name='agregar-manifiesto'
    ),
    url(
        r'^manifiesto/update/(?P<pk>\d+)/$',
        views.UpdateManifest.as_view(),
        name='update-manifiesto'
    ),
    url(
        r'^manifiesto/full/(?P<pk>\d+)/$',
        views.FullManifestView.as_view(),
        name='full-manifiesto'
    ),
    url(
        r'^manifiesto/delete/(?P<pk>\d+)/$',
        views.AnulateManifestView.as_view(),
        name='eliminar-manifiesto'
    ),
    url(
        r'^manifiesto/ver/(?P<pk>\d+)/$',
        views.DetailManifestView.as_view(),
        name='visualizar-manifiesto'
    ),
    url(
        r'^manifiesto/crear-manifiesto/sub-contrata$',
        views.ThirdManifestView.as_view(),
        name='agregar-sub_contrata'
    ),
    url(
        r'^manifiesto/completar-manifiesto/(?P<pk>\d+)/$',
        views.Complete_Manifest.as_view(),
        name='completar-manifiesto'
    ),
    # url para reportes manifiesto
    url(
        r'^manifiesto/crear-remision/(?P<pk>\d+)/$',
        views.RemissionView.as_view(),
        name='register-remission'
    ),
    url(
        r'^manifiesto/reporte-manifiesto/(?P<pk>\d+)/$',
        views.ReportManifest.as_view(),
        name='reporte-manifiesto'
    ),
    url(
        r'^manifiesto/detalle-manifiesto/(?P<pk>\d+)/(?P<br>\d+)/$',
        views.ReportDetailManifest.as_view(),
        name='detalle-manifiesto'
    ),
    # url para rececpcionde notas de ingreso
    url(
        r'^manifiesto/recepcion/lista/$',
        views.Manifest_no_Reception.as_view(),
        name='manifiesto-no-recepcionado'
    ),
    url(
        r'^manifiesto/recepcion/registrar/(?P<pk>\d+)/$',
        views.Slip_Reception.as_view(),
        name='registrar-recepcion'
    ),
]

nshipping/apps/salida/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^salidas/add/$',
        views.RegisterExpenditur.as_view(),
        name='agregar-egreso'
    ),
    url(
        r'^salidas/ver/(?P<pk>\d+)/$',
        views.DetailExpenditur.as_view(),
        name='visualizar-egreso'
    ),
    url(
        r'^salidas/listar/$',
        views.ListExpenditur.as_view(),
        name='listar-egreso'
    ),
    url(
        r'^salidas/anular/(?P<pk>\d+)/$',
        views.AnulateExpenditur.as_view(),
        name='anular-egreso'
    ),
    url(
        r'^salidas/reporte/lista/(?P<pk>\d+)/$',
        views.CountableCahs.as_view(),
        name='reporte-salidas'
    ),
    url(
        r'^salidas/reporte/lista/$',
        views.ListActives.as_view(),
        name='users-activos'
    ),
]

nshipping/apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^$',
        views.LogIn.as_view(),
        name='login'
    ),
    url(
        r'^administrador/verificar/(?P<pk>\d+)/$',
        views.LogAdmin.as_view(),
        name='login-admin'
    ),
    url(
        r'^users/salir/$',
        'apps.users.views.LogOut',
        name='logout'
    ),
    url(
        r'^panel/$',
        views.PanelView.as_view(),
        name='panel'
    ),
    url(
        r'^panel/usuario/entrega-envio/$',
        views.Panel2View.as_view(),
        name='entrega_envio'
    ),
    url(
        r'^panel/usuario/entrega-envio/100/$',
        views.Panel3View.as_view(),
        name='entrega_detalle'
    ),
]

nshipping/nshipping/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # urls para la aplicacion users
    url(r'^', include('apps.users.urls', namespace="users_app")),
    # urls para la aplicacion de ingreso
    url(r'^', include('apps.ingreso.urls', namespace="ingreso_app")),
    # urls para la aplicacion de manifiesto
    url(r'^', include('apps.manifiesto.urls', namespace="manifiesto_app")),
    # urls para la aplicacion de perfiles
    url(r'^', include('apps.profiles.urls', namespace="profiles_app")),
    # urls para la aplicacion de salida
    url(r'^', include('apps.salida.urls', namespace="salida_app")),

    url(r'^admin/', include(admin.site.urls)),
]

nshipping/apps/manifiesto/models.py
# -*- encoding: utf-8 -*-
# import utils
from model_utils.models import TimeStampedModel
# import django
from django.db import models
from django.conf import settings
from django.utils import timezone
# import local
from apps.ingreso.models import Branch, DepositSlip
from apps.users.models import User


class Car(models.Model):
    STATE_CHOICES = (
        ('0', 'Propio'),
        ('1', 'Sub Contrata'),
    )
    name = models.CharField(
        'Denominacion',
        max_length=50,
    )
    plaque = models.CharField(
        'Placa',
        max_length=10
    )
    marca = models.CharField(
        'Marca',
        max_length=70,
    )
    code_ssettings_car = models.CharField(
        'Codigo de Configuracion vehicular',
        max_length=6
    )
    constancy_inscription = models.CharField(
        'N° de Contancia de Inscripcion',
        max_length=12,
    )
    condition = models.CharField(
        'Condicion',
        choices=STATE_CHOICES,
        max_length=11,
    )
    canceled = models.BooleanField(
        'anulado',
        default=False,
        editable=False
    )

    class Meta:
        verbose_name = "Carro"
        verbose_name_plural = "Carros"

    def __unicode__(self):
        return self.plaque


class Driver(models.Model):
    dni = models.CharField(
        'Dni',
        max_length=8,
    )
    full_name = models.CharField(
        'Nombres',
        max_length=100,
    )
    license = models.CharField(
        'Brebete',
        max_length=10
    )
    addreess = models.CharField(
        'Direccion',
        max_length=150
    )
    phone = models.CharField(
        'Telefono',
        max_length=10
    )
    email = models.EmailField()
    date_birth = models.DateField(
        'fecha de nacimiento',
        blank=True,
        null=True,
    )
    canceled = models.BooleanField(
        'anulado',
        default=False,
        editable=False
    )

    class Meta:
        verbose_name = "Conductor"
        verbose_name_plural = "Conductores"

    def __unicode__(self):
        return self.full_name


class ManangerManifest(models.Manager):

    def manifest_by_user(self, branch):
        #recuperamos la lista de manifiestos enviados
        manifest_query = self.filter(reception=False, state=True)
        # recorremos el manifiesto
        lista = []
        for manifest in manifest_query:
            existe = False
            for slip in manifest.deposit_slip.all():
                if slip.destination == branch:
                    print '======pertenece al manifiesto====='
                    existe = True
            # verificamos si se encontro alguna sucursal
            if existe is True:
                print '======se agrega el manifiesto======='
                lista.append(manifest)
        # devolvemos la lista
        return lista


class Manifest(TimeStampedModel):
    driver = models.ForeignKey(Driver)
    car = models.ForeignKey(Car)
    deposit_slip = models.ManyToManyField(
        DepositSlip,
    )
    destination = models.ForeignKey(Branch)
    origin = models.ForeignKey(
        Branch,
        related_name="Branch_origin",
    )
    user_created = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="manifest_user_created"
    )
    user_modified = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="manifest_user_modified",
        blank=True,
        null=True
    )
    date_shipping = models.DateField(
        'fecha de Traslado',
    )
    state = models.BooleanField('Estado')
    reception = models.BooleanField(
        default=False,
        editable=True,
    )
    canceled = models.BooleanField(
        'anulado',
        default=False,
        editable=False
    )
    arrive = models.BooleanField(
        'arrivo',
        default=False,
    )

    objects = ManangerManifest()

    class Meta:
        verbose_name = "Manifiesto"
        verbose_name_plural = "Manifiestos"

    def __unicode__(self):
        return "%s - %s" % (str(self.driver), str(self.car))


class Observation(models.Model):
    description = models.TextField()
    manifest = models.ForeignKey(Manifest)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        verbose_name = "Observation"
        verbose_name_plural = "Observations"

    def __unicode__(self):
        return self.manifest


class SubContract(models.Model):
    manifest = models.ForeignKey(Manifest)
    full_name = models.CharField(
        'Nombres/Razon social',
        max_length=70,
    )
    ruc = models.CharField(
        'Ruc',
        max_length=50,
    )
    observation = models.CharField(
        'Observaciones',
        max_length=50,
    )
    canceled = models.BooleanField(
        'anulado',
        default=False,
        editable=False
    )

    class Meta:
        verbose_name = "SubContract"
        verbose_name_plural = "SubContracts"

    def __unicode__(self):
        return self.full_name

nshipping/templates/manifiesto/car/delete.html
{% extends "ingreso/nota_ingreso/base_nota.html" %}

{% block title %}eliminar vehiculo{% endblock title %}

{% block sidenav %}

    <li>
        <a class="active" href="{% url 'ingreso_app:nota-ingreso' %}"><i class="fa fa-fw fa-truck"></i> Nota De Ingreso</a>
    </li>
    <li>
        <a href="{% url 'ingreso_app:lista_envio' %}"><i class="fa fa-fw fa-paper-plane-o"></i> Entrega De Envios</a>
    </li>
    <li>
        <a href="{% url 'manifiesto_app:manifiesto-no-recepcionado' %}"><i class="fa fa-fw fa-cubes"></i> Recepcion de Paquetes</a>
    </li>
    <li>
        <a href="{% url 'salida_app:listar-egreso' %}"><i class="fa fa-fw fa-money"></i> Registro de Egresos</a>
    </li>

    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#caja">
            <i class="fa fa-fw fa-bullseye"></i>
            Caja Chica
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="caja" class="collapse">
            <li>
                <a href="{% url 'users_app:login-admin' user.pk %}">Cuadrar Caja</a>
            </li>
            <li>
                <a href="{% url 'salida_app:users-activos' %}">Consultar Agencias</a>
            </li>
        </ul>
    </li>

    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#manifiesto">
            <i class="fa fa-fw fa-bullseye"></i>
            Manifiesto
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="manifiesto" class="collapse">
            <li>
                <a href="{% url 'manifiesto_app:listar-manifiesto' %}">Manifiesto En Curso</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:agregar-manifiesto' %}">Manifiesto Empresa</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:agregar-sub_contrata' %}">Manifiesto por Sub-Contrata</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#mantenimiento">
            <i class="fa fa-fw fa-cogs"></i>
            Mantenimiento
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="mantenimiento" class="collapse">
            <li>
                <a href="{% url 'ingreso_app:listar-branch' %}">Sucursales</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:listar-carro' %}">Vehiculos</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:listar-conductor' %}">Conductores</a>
            </li>
        </ul>
    </li>

{% endblock sidenav %}

{% block content_panel %}

{% if user.is_superuser %}

    <div class="row">
        <div class="col-xs-12">
            <h3 class="page-header title-quilla">Eliminar Vehículo</h3>
        </div>
    </div>

    <div class="row box-section">

        <div class="col-md-12">

            <form role="form" action="{% url 'manifiesto_app:eliminar-carro' car.id %}" method="POST">{% csrf_token %}
                <p class="">¿Desea eliminar el Vehículo <strong>{{ car.name }}</strong>?</p>
                <dl class="dl-horizontal">
                    <dt>Placa:</dt>
                    <dd>{{ car.plaque }}</dd>
                    <dt>Marca:</dt>
                    <dd>{{ car.marca }}</dd>
                    <dt>Cod. Configuración Vehícular:</dt>
                    <dd>{{ car.code_ssettings_car }}</dd>
                    <dt>N° de Constancia de Inscripción:</dt>
                    <dd>{{ car.constancy_inscription }}</dd>
                    <dt>Condición:</dt>
                    <dd>{{ car.get_condition_display }}</dd>
                </dl>
                <button type="submit" class="btn btn-danger">Sí</button>
                <a href="{% url 'manifiesto_app:listar-carro' %}" class="btn btn-default">No</a>
            </form>

        </div><!-- col-md-12 -->

    </div><!-- /row -->
{% else %}
    <h3>Necesita Permisos de Administrador</h3>
{% endif %}
{% endblock content_panel %}

nshipping/templates/manifiesto/car/detail.html
{% extends "ingreso/nota_ingreso/base_nota.html" %}

{% block title %}detalle vehiculo{% endblock title %}

{% block sidenav %}

    <li>
        <a class="active" href="{% url 'ingreso_app:nota-ingreso' %}"><i class="fa fa-fw fa-truck"></i> Nota De Ingreso</a>
    </li>
    <li>
        <a href="{% url 'ingreso_app:lista_envio' %}"><i class="fa fa-fw fa-paper-plane-o"></i> Entrega De Envios</a>
    </li>
    <li>
        <a href="{% url 'manifiesto_app:manifiesto-no-recepcionado' %}"><i class="fa fa-fw fa-cubes"></i> Recepcion de Paquetes</a>
    </li>
    <li>
        <a href="{% url 'salida_app:listar-egreso' %}"><i class="fa fa-fw fa-money"></i> Registro de Egresos</a>
    </li>

    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#caja">
            <i class="fa fa-fw fa-bullseye"></i>
            Caja Chica
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="caja" class="collapse">
            <li>
                <a href="{% url 'users_app:login-admin' user.pk %}">Cuadrar Caja</a>
            </li>
            <li>
                <a href="{% url 'salida_app:users-activos' %}">Consultar Agencias</a>
            </li>
        </ul>
    </li>

    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#manifiesto">
            <i class="fa fa-fw fa-bullseye"></i>
            Manifiesto
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="manifiesto" class="collapse">
            <li>
                <a href="{% url 'manifiesto_app:listar-manifiesto' %}">Manifiesto En Curso</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:agregar-manifiesto' %}">Manifiesto Empresa</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:agregar-sub_contrata' %}">Manifiesto por Sub-Contrata</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#mantenimiento">
            <i class="fa fa-fw fa-cogs"></i>
            Mantenimiento
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="mantenimiento" class="collapse">
            <li>
                <a href="{% url 'ingreso_app:listar-branch' %}">Sucursales</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:listar-carro' %}">Vehiculos</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:listar-conductor' %}">Conductores</a>
            </li>
        </ul>
    </li>

{% endblock sidenav %}

{% block content_panel %}

    <div class="row">
        <div class="col-xs-12">
            <h3 class="page-header title-quilla">Detalle Vehículo</h3>
        </div>
    </div>

     <div class="row box-section">
        <div class="col-xs-12">
            <dl class="dl-horizontal">
                <dt>Denominación:</dt>
                <dd>{{ car.name }}</dd>
                <dt>Placa:</dt>
                <dd>{{ car.plaque }}</dd>
                <dt>Marca:</dt>
                <dd>{{ car.marca }}</dd>
                <dt>Cod. Configuración Vehícular:</dt>
                <dd>{{ car.code_ssettings_car }}</dd>
                <dt>N° de Constancia de Inscripción:</dt>
                <dd>{{ car.constancy_inscription }}</dd>
                <dt>Condición:</dt>
                <dd>{{ car.get_condition_display }}</dd>
            </dl>

        </div>

        <div class="col-xs-12">
            <a class="btn btn-warning" role="button" href="{% url 'manifiesto_app:actualizar-carro' car.pk %}" ><i class="fa fa-pencil fa-lg"></i> Editar</a>
            <a class="btn btn-default" role="button" href="{% url 'manifiesto_app:listar-carro' %}" >Regresar a lista</a>
        </div>
    </div>

{% endblock content_panel %}

nshipping/templates/manifiesto/car/list.html
{% extends "ingreso/nota_ingreso/base_nota.html" %}

{% block title %}lista de vehiculos{% endblock title %}

{% block sidenav %}

    <li>
        <a class="active" href="{% url 'ingreso_app:nota-ingreso' %}"><i class="fa fa-fw fa-truck"></i> Nota De Ingreso</a>
    </li>
    <li>
        <a href="{% url 'ingreso_app:lista_envio' %}"><i class="fa fa-fw fa-paper-plane-o"></i> Entrega De Envios</a>
    </li>
    <li>
        <a href="{% url 'manifiesto_app:manifiesto-no-recepcionado' %}"><i class="fa fa-fw fa-cubes"></i> Recepcion de Paquetes</a>
    </li>
    <li>
        <a href="{% url 'salida_app:listar-egreso' %}"><i class="fa fa-fw fa-money"></i> Registro de Egresos</a>
    </li>

    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#caja">
            <i class="fa fa-fw fa-bullseye"></i>
            Caja Chica
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="caja" class="collapse">
            <li>
                <a href="{% url 'users_app:login-admin' user.pk %}">Cuadrar Caja</a>
            </li>
            <li>
                <a href="{% url 'salida_app:users-activos' %}">Consultar Agencias</a>
            </li>
        </ul>
    </li>

    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#manifiesto">
            <i class="fa fa-fw fa-bullseye"></i>
            Manifiesto
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="manifiesto" class="collapse">
            <li>
                <a href="{% url 'manifiesto_app:listar-manifiesto' %}">Manifiesto En Curso</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:agregar-manifiesto' %}">Manifiesto Empresa</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:agregar-sub_contrata' %}">Manifiesto por Sub-Contrata</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#mantenimiento">
            <i class="fa fa-fw fa-cogs"></i>
            Mantenimiento
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="mantenimiento" class="collapse">
            <li>
                <a href="{% url 'ingreso_app:listar-branch' %}">Sucursales</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:listar-carro' %}">Vehiculos</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:listar-conductor' %}">Conductores</a>
            </li>
        </ul>
    </li>

{% endblock sidenav %}

{% block content_panel %}

{% if user.is_superuser %}

    <div class="row">
        <div class="col-xs-12">
            <h3 class="page-header title-quilla">Lista de Vehículos</h3>
        </div>
    </div>

    <div class="row">
        <div class="clo-xs-12">
            <div class="quilla-add">
                <span class="quilla-cantitem">
                    Tienes <span class="label label-warning">{{ cantidad }}</span> Vehículos Disponibles
                </span>
                <a class="btn btn-quilla pull-right" href="{% url 'manifiesto_app:agregar-carro' %}">
                    <span class="fa fa-plus"></span> Crear Nuevo Vehículo
                </a>
            </div>

        </div>
    </div><!-- page-header -->

    <div class="row">
        <div class="col-xs-12">
            <div class="table-responsive">

                <table class="table table-bordered table-hover table-condensed table-quilla">
                    <thead>
                        <tr>
                            <th>Denominación</th>
                            <th>Placa</th>
                            <th>Marca</th>
                            <th>Tipo</th>
                            <th class="text-center">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for car in  carros %}
                            <tr>
                                <td>{{ car.name }}</td>
                                <td>{{ car.plaque }}</td>
                                <td>{{ car.marca }}</td>
                                <td>
                                    {% if car.condition = '0' %}
                                      <span class="label label-success">Propio</span>
                                    {% else %}
                                        <span class="label label-warning">Sub Contrata</span>
                                    {% endif %}

                                </td>

                                <td class="text-center">
                                    <a href="{% url 'manifiesto_app:visualizar-carro' car.pk %}" class="btn btn-sm btn-success"><i class="fa fa-fw fa-eye"></i></a>
                                    <a href="{% url 'manifiesto_app:actualizar-carro' car.pk %}" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <a href="{% url 'manifiesto_app:eliminar-carro' car.pk %}" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                                </td>
                            </tr>
                        {% empty %}
                                <td colspan="7">Lo sentimos no hay vehículos disponibles</td>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% else %}
    <h3>Necesita Permisos de Administrador</h3>
{% endif %}

{% endblock content_panel %}