nshipping/apps/ingreso/urls.py
from django.conf.urls import url, patterns, include
from rest_framework import routers
from . import views
from .viewsets import ClientViewSet, ClienteViewSet
from .models import Client

router = routers.SimpleRouter()
router.register(r'clientes',ClienteViewSet)
router.register(r'cliente', ClientViewSet,base_name = Client)
urlpatterns = [
    url(r'^api/',include(router.urls)),
    url(
        r'^panel/nota-ingreso/$',
        views.DepositSlipView.as_view(),
        name='nota-ingreso'
    ),
    url(
        r'^panel/envio/(?P<pk>\d+)/imprimir/$',
        views.EnvioPrintView.as_view(),
        name='print-envio'
    ),
    url(
        r'^panel/imprimir/nota-ingreso/(?P<pk>\d+)/$',
        views.ReportNotaView.as_view(),
        name='print-nota-ingreso'
    ),
    url(
        r'^panel/imprimir/guia/(?P<pk>\d+)/$',
        views.ReportGuiaView.as_view(),
        name='print-guia'
    ),
    url(
        r'^panel/imprimir/comprobante/(?P<pk>\d+)/$',
        views.ReportComprobanteView.as_view(),
        name='print-comprobante'
    ),
    url(
        r'^panel/entregar-envio/$',
        views.DeliverView.as_view(),
        name='lista_envio'
    ),
    url(
        r'^panel/entregar-envio/(?P<pk>\d+)/$',
        views.DetailDeliverView.as_view(),
        name='detalle_envio'
    ),
    # url para manteniminetos de sucursales
    url(
        r'^sucursales/listar/$',
        views.ListBranchView.as_view(),
        name='listar-branch'
    ),
    url(
        r'^sucursales/add/$',
        views.RegisterBranchView.as_view(),
        name='agregar-branch'
    ),
    url(
        r'^sucursales/update/(?P<pk>\d+)$',
        views.UpdateBranchView.as_view(),
        name='actualizar-branch'
    ),
    url(
        r'^sucursales/detail/(?P<pk>\d+)$',
        views.DetailBranchView.as_view(),
        name='detalle-branch'
    ),
    url(
        r'^sucursales/delete/(?P<pk>\d+)$',
        views.DeleteBranchView.as_view(),
        name='eliminar-branch'
    ),
]

nshipping/apps/manifiesto/urls.py
from django.conf.urls import url, patterns, include
from rest_framework import routers
from django.conf.urls import url
from .models import Manifest
from .viewsets import ManifestViewSet
from . import views


router = routers.SimpleRouter()
router.register(r'manifiesto', ManifestViewSet,base_name = Manifest)

urlpatterns = [
    url(r'^api/',include(router.urls)),
    url(
        r'^manifiesto/car/listar/$',
        views.ListCarView.as_view(),
        name='listar-carro'
    ),
    url(
        r'^manifiesto/car/add/$',
        views.RegisterCarView.as_view(),
        name='agregar-carro'
    ),
    url(
        r'^manifiesto/car/update/(?P<pk>\d+)/$',
        views.UpdateCarView.as_view(),
        name='actualizar-carro'
    ),
    url(
        r'^manifiesto/car/delete/(?P<pk>\d+)/$',
        views.DeleteCarView.as_view(),
        name='eliminar-carro'
    ),
    url(
        r'^manifiesto/car/detail/(?P<pk>\d+)/$',
        views.DetailCarView.as_view(),
        name='visualizar-carro'
    ),
    # url conductor
    url(
        r'^manifiesto/driver/listar/$',
        views.ListDriverView.as_view(),
        name='listar-conductor'
    ),
    url(
        r'^manifiesto/driver/add/$',
        views.RegisterDriverView.as_view(),
        name='agregar-conductor'
    ),
    url(
        r'^manifiesto/driver/update/(?P<pk>\d+)/$',
        views.UpdateDriverView.as_view(),
        name='actualizar-conductor'
    ),
    url(
        r'^manifiesto/driver/detail/(?P<pk>\d+)/$',
        views.DetailDriverView.as_view(),
        name='visualizar-conductor'
    ),
    url(
        r'^manifiesto/driver/delete/(?P<pk>\d+)/$',
        views.DeleteDriverView.as_view(),
        name='eliminar-conductor'
    ),
    # url para mantenimietno manifiesto
    url(
        r'^manifiesto/listar/$',
        views.ManifestList.as_view(),
        name='listar-manifiesto'
    ),
    url(
        r'^manifiesto/crear-manifiesto/$',
        views.ManifestView.as_view(),
        name='agregar-manifiesto'
    ),
    url(
        r'^manifiesto/update/(?P<pk>\d+)/$',
        views.UpdateManifest.as_view(),
        name='update-manifiesto'
    ),
    url(
        r'^manifiesto/full/(?P<pk>\d+)/$',
        views.FullManifestView.as_view(),
        name='full-manifiesto'
    ),
    url(
        r'^manifiesto/delete/(?P<pk>\d+)/$',
        views.AnulateManifestView.as_view(),
        name='eliminar-manifiesto'
    ),
    url(
        r'^manifiesto/ver/(?P<pk>\d+)/$',
        views.DetailManifestView.as_view(),
        name='visualizar-manifiesto'
    ),
    url(
        r'^manifiesto/crear-manifiesto/sub-contrata$',
        views.ThirdManifestView.as_view(),
        name='agregar-sub_contrata'
    ),
    url(
        r'^manifiesto/completar-manifiesto/(?P<pk>\d+)/$',
        views.Complete_Manifest.as_view(),
        name='completar-manifiesto'
    ),
    # url para reportes manifiesto
    url(
        r'^manifiesto/crear-remision/(?P<pk>\d+)/$',
        views.RemissionView.as_view(),
        name='register-remission'
    ),
    url(
        r'^manifiesto/reporte-manifiesto/(?P<pk>\d+)/$',
        views.ReportManifest.as_view(),
        name='reporte-manifiesto'
    ),
    url(
        r'^manifiesto/detalle-manifiesto/(?P<pk>\d+)/(?P<br>\d+)/$',
        views.ReportDetailManifest.as_view(),
        name='detalle-manifiesto'
    ),
    # url para rececpcionde notas de ingreso
    url(
        r'^manifiesto/recepcion/lista/$',
        views.Manifest_no_Reception.as_view(),
        name='manifiesto-no-recepcionado'
    ),
    url(
        r'^manifiesto/recepcion/registrar/(?P<pk>\d+)/$',
        views.Slip_Reception.as_view(),
        name='registrar-recepcion'
    ),
]

nshipping/apps/salida/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^salidas/add/$',
        views.RegisterExpenditur.as_view(),
        name='agregar-egreso'
    ),
    url(
        r'^salidas/ver/(?P<pk>\d+)/$',
        views.DetailExpenditur.as_view(),
        name='visualizar-egreso'
    ),
    url(
        r'^salidas/listar/$',
        views.ListExpenditur.as_view(),
        name='listar-egreso'
    ),
    url(
        r'^salidas/anular/(?P<pk>\d+)/$',
        views.AnulateExpenditur.as_view(),
        name='anular-egreso'
    ),
    url(
        r'^salidas/reporte/lista/(?P<pk>\d+)/$',
        views.CountableCahs.as_view(),
        name='reporte-salidas'
    ),
    url(
        r'^salidas/reporte/lista/$',
        views.ListActives.as_view(),
        name='users-activos'
    ),
]

nshipping/apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^$',
        views.LogIn.as_view(),
        name='login'
    ),
    url(
        r'^administrador/verificar/(?P<pk>\d+)/$',
        views.LogAdmin.as_view(),
        name='login-admin'
    ),
    url(
        r'^users/salir/$',
        'apps.users.views.LogOut',
        name='logout'
    ),
    url(
        r'^panel/$',
        views.PanelView.as_view(),
        name='panel'
    ),
    url(
        r'^panel/usuario/entrega-envio/$',
        views.Panel2View.as_view(),
        name='entrega_envio'
    ),
    url(
        r'^panel/usuario/entrega-envio/100/$',
        views.Panel3View.as_view(),
        name='entrega_detalle'
    ),
]

nshipping/nshipping/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # urls para la aplicacion users
    url(r'^', include('apps.users.urls', namespace="users_app")),
    # urls para la aplicacion de ingreso
    url(r'^', include('apps.ingreso.urls', namespace="ingreso_app")),
    # urls para la aplicacion de manifiesto
    url(r'^', include('apps.manifiesto.urls', namespace="manifiesto_app")),
    # urls para la aplicacion de perfiles
    url(r'^', include('apps.profiles.urls', namespace="profiles_app")),
    # urls para la aplicacion de salida
    url(r'^', include('apps.salida.urls', namespace="salida_app")),

    url(r'^admin/', include(admin.site.urls)),
]

nshipping/apps/manifiesto/forms.py
# -*- encoding: utf-8 -*-

from django import forms
from django.forms.models import ModelMultipleChoiceField

from .models import Car, Driver, Manifest

from apps.ingreso.models import Dues, DepositSlip, Branch
from apps.profiles.models import Profile


class CarForm(forms.ModelForm):
    '''
    Formulario para agregar un carro.
    '''
    class Meta:
        model = Car
        fields = ("__all__")

        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrese una Denominacion'
                }
            ),
            'plaque': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrese Nro de Placa'
                }
            ),
            'marca': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrese Marca del Vehiculo'
                }
            ),
            'code_ssettings_car': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrese Codigo de Configuracion Vehicular'
                }
            ),
            'constancy_inscription': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrese Nro de Cosntacia de Inscripcion'
                }
            ),
            'condition': forms.Select(
                attrs={'class': 'form-control input-sm'}
            ),
        }


class DriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ("__all__")

        widgets = {
            'dni': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrese Nro de DNI'
                }
            ),
            'full_name': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrese Nombre Completo'
                }
            ),
            'license': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrese Nro de Licencia de Conducir'
                }
            ),
            'addreess': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrese una Direccion'
                }
            ),
            'phone': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrse Nro de Telefono o Celular'
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': 'Ingrese Direccion de Correo Electronico'
                }
            ),

            'date_birth': forms.DateInput(
                attrs={
                    'class': 'form-control input-sm datepicker',
                    'placeholder': 'Seleccione un fecha'
                },
                format='%d/%m/%Y'
            ),
        }

    def clean_dni(self):
        dni = self.cleaned_data['dni']
        if not dni.isdigit():
            msj = 'el Dni solo deben contener numeros'
            self.add_error('dni', msj)
        elif len(dni) != 8:
            msj = 'el Dni solo puede tener 8 digitos'
            self.add_error('dni', msj)
        else:
            return dni


class FilterForm(forms.Form):
    # formulario para busquedas por filtro
    destination = forms.CharField(label='Destino', required=False)


class ManifestForm(forms.ModelForm):
    """ Formulario para el Registro de Manifiesto"""
    class Meta:
        model = Manifest
        fields = (
            'driver',
            'car',
            'destination',
            'origin',
            'date_shipping',
        )

        widgets = {
            'driver': forms.Select(
                attrs={'class': 'form-control input-sm'}
            ),
            'car': forms.Select(
                attrs={'class': 'form-control input-sm'}
            ),
            'destination': forms.Select(
                attrs={'class': 'form-control input-sm'}
            ),
            'origin': forms.Select(
                attrs={'class': 'form-control input-sm'}
            ),
            'date_shipping': forms.DateInput(
                attrs={
                    'class': 'form-control input-sm datepicker',
                    'placeholder': 'Seleccione una fecha'
                },
                format='%d/%m/%Y'
            ),
        }

    def __init__(self, *args, **kwargs):
        super(ManifestForm, self).__init__(*args, **kwargs)
        self.fields['car'].queryset = Car.objects.filter(
            condition='0',
            canceled=False
        )
        self.fields['driver'].queryset = Driver.objects.filter(
            canceled=False,
        )


class ThirdManifestForm(ManifestForm):
    """
    Formulario para el Registro de Manifiesto
    """
    full_name = forms.CharField(
        label='Nombres/RazonSocial',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-detail',
                'placeholder': 'Ingrese nombres o razón social',
            }
        ),
    )
    ruc = forms.CharField(
        label='Ruc',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-detail',
                'placeholder': 'Ingrese numero de ruc',
            }
        ),
    )
    observations = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control input-detail',
                'placeholder': 'Ingrese observación',
                'rows': '4'
            }
        ),
    )

    class Meta(ManifestForm.Meta):
        model = Manifest
        fields = (
            'driver',
            'car',
            'destination',
            'origin',
            'date_shipping',
        )

    def __init__(self, *args, **kwargs):
        super(ThirdManifestForm, self).__init__(*args, **kwargs)
        self.fields['car'].queryset = Car.objects.filter(
            condition='1',
            canceled=False
        )
        self.fields['driver'].queryset = Driver.objects.filter(
            canceled=False,
        )

    def clean_ruc(self):
        ruc = self.cleaned_data['ruc']
        if (len(ruc) > 0) and (not ruc.isdigit()):
            msj = 'el Ruc solo deben contener numeros'
            self.add_error('ruc', msj)
        elif len(ruc) != 11 and len(ruc) > 0:
            msj = 'el Ruc solo puede tener 11 digitos'
            self.add_error('ruc', msj)
        else:
            return ruc


class RemissionForm(forms.Form):
    manifest = forms.ModelChoiceField(
        label='Manifiesto',
        queryset=None,
        widget=forms.Select(
            attrs={
                'class': 'form-control input-sm',
                'ng-model':'vm.remission',
                'ng-change':'vm.change(vm.remission)',
                'placeholder': 'Pulse para Seleccionar',
            }
        ),
    )

    def __init__(self, user, pk, *args, **kwargs):
        super(RemissionForm, self).__init__(*args, **kwargs)
        sucursal = Profile.objects.get(user=user).branch
        self.fields['manifest'].queryset = Manifest.objects.filter(
            state=False,
            origin=sucursal,
            canceled=False,
        )


# formulario para recepcionar notas de ingreso
class ReceptionForm(forms.Form):
    deposit_slip = forms.ModelMultipleChoiceField(
        queryset=None,
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )

    def __init__(self, pk, user, *args, **kwargs):
        super(ReceptionForm, self).__init__(*args, **kwargs)
        # recupera sucursal
        profile_query = Profile.objects.filter(user=user)
        if profile_query.count() > 0:
            branch = profile_query[0].branch.id
            # realizamos la consulta
            deposit_slip = DepositSlip.objects.slip_by_manifest(
                pk,
                branch,
            )
            # asignamos la consulta
            self.fields['deposit_slip'].queryset = deposit_slip
            self.fields['deposit_slip'].label_from_instance = \
                lambda obj: "%s %s - %s - %s - %s - %s" % (
                    obj.number,
                    obj.serie,
                    obj.origin,
                    obj.sender,
                    obj.addressee,
                    obj.destination,
                )
        else:
            self.fields['deposit_slip'].queryset = None

nshipping/templates/manifiesto/manifest/detalle-reporte.html
<html>
<head>
    <title></title>
</head>
<body>
<html>
<head>
    <title></title>
</head>
<body>
    {{slips}}
    <table class="hoverable centered bordered responsive-table">
        <thead>
          <tr>
              <th>codigo</th>
              <th>serie</th>
              <th>numero</th>
              <th>destino</th>             
          </tr>
        </thead>
        <tbody>
                {% for s in slips %}
                 <tr>
                    <td>{{s.pk}}</td>
                    <td>{{s.serie}}</td>
                    <td>{{s.number}}</td>
                    <td>{{s.destination}}</td> 
                </tr>
                {%endfor%}        
        </tbody>
</table>
</body>
</html>
</body>
</html>

nshipping/templates/manifiesto/manifest/list.html
{% extends "ingreso/nota_ingreso/base_nota.html" %}

{% block sidenav %}

    <li>
        <a class="active" href="{% url 'ingreso_app:nota-ingreso' %}"><i class="fa fa-fw fa-truck"></i> Nota De Ingreso</a>
    </li>
    <li>
        <a href="{% url 'ingreso_app:lista_envio' %}"><i class="fa fa-fw fa-paper-plane-o"></i> Entrega De Envios</a>
    </li>
    <li>
        <a href="{% url 'manifiesto_app:manifiesto-no-recepcionado' %}"><i class="fa fa-fw fa-cubes"></i> Recepcion de Paquetes</a>
    </li>
    <li>
        <a href="{% url 'salida_app:listar-egreso' %}"><i class="fa fa-fw fa-money"></i> Registro de Egresos</a>
    </li>

    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#caja">
            <i class="fa fa-fw fa-bullseye"></i>
            Caja Chica
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="caja" class="collapse">
            <li>
                <a href="{% url 'users_app:login-admin' user.pk %}">Cuadrar Caja</a>
            </li>
            <li>
                <a href="{% url 'salida_app:users-activos' %}">Consultar Agencias</a>
            </li>
        </ul>
    </li>

    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#manifiesto">
            <i class="fa fa-fw fa-bullseye"></i>
            Manifiesto
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="manifiesto" class="collapse">
            <li>
                <a href="{% url 'manifiesto_app:listar-manifiesto' %}">Manifiesto En Curso</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:agregar-manifiesto' %}">Manifiesto Empresa</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:agregar-sub_contrata' %}">Manifiesto por Sub-Contrata</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#mantenimiento">
            <i class="fa fa-fw fa-cogs"></i>
            Mantenimiento
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="mantenimiento" class="collapse">
            <li>
                <a href="{% url 'ingreso_app:listar-branch' %}">Sucursales</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:listar-carro' %}">Vehiculos</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:listar-conductor' %}">Conductores</a>
            </li>
        </ul>
    </li>

{% endblock sidenav %}

{% block content_panel %}

{% if user.is_superuser %}

    <div class="row">
        <div class="col-xs-12">
            <h3 class="page-header title-quilla">Lista de Manifiestos no Completos</h3>
        </div>
    </div>

    <div class="row">
        <div class="clo-xs-12">
            <div class="quilla-add">
                <span class="quilla-cantitem">
                    Tienes <span class="label label-warning">{{ cantidad }}</span> manifiestos no completos
                </span>
            </div>

        </div>
    </div><!-- page-header -->

    <div class="row">
        <div class="col-xs-12">
            <div class="table-responsive">

                <table class="table table-bordered table-hover table-condensed table-quilla">
                    <thead>
                        <tr>
                            <th>Vehículo</th>
                            <th>Conductor</th>
                            <th>Dirección Partida</th>
                            <th>Dirección LLegada</th>
                            <th>Fecha Traslado</th>
                            <th class="text-center">Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for manifest in  manifests %}
                            {% if manifest.arrive == True  %}
                                <tr class="warning">
                                    <td>{{ manifest.car }}</td>
                                    <td>{{ manifest.driver }}</td>
                                    <td>{{ manifest.origin }}</td>
                                    <td>{{ manifest.destination }}</td>
                                    <td>{{ manifest.date_shipping }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'manifiesto_app:full-manifiesto' manifest.pk %}" class="btn btn-sm btn-success"><i class="fa fa-fw fa-check"></i></a>
                                        <a href="{% url 'manifiesto_app:update-manifiesto' manifest.pk %}" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-pencil"></i></a>
                                        <a href="{% url 'manifiesto_app:completar-manifiesto' manifest.pk %}" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-thumbs-up"></i></a>
                                    </td>
                                </tr>
                            {% else %}
                              {% if manifest.state == True %}
                                <tr class="success">
                                    <td>{{ manifest.car }}</td>
                                    <td>{{ manifest.driver }}</td>
                                    <td>{{ manifest.origin }}</td>
                                    <td>{{ manifest.destination }}</td>
                                    <td>{{ manifest.date_shipping }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'manifiesto_app:full-manifiesto' manifest.pk %}" class="btn btn-sm btn-success"><i class="fa fa-fw fa-check"></i></a>
                                        <a href="{% url 'manifiesto_app:update-manifiesto' manifest.pk %}" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-pencil"></i></a>
                                        <a href="{% url 'manifiesto_app:completar-manifiesto' manifest.pk %}" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-thumbs-up"></i></a>
                                    </td>
                                </tr>
                                {% else %}
                                  <tr>
                                    <td>{{ manifest.car }}</td>
                                    <td>{{ manifest.driver }}</td>
                                    <td>{{ manifest.origin }}</td>
                                    <td>{{ manifest.destination }}</td>
                                    <td>{{ manifest.date_shipping }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'manifiesto_app:full-manifiesto' manifest.pk %}" class="btn btn-sm btn-success"><i class="fa fa-fw fa-check"></i></a>
                                        <a href="{% url 'manifiesto_app:update-manifiesto' manifest.pk %}" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-pencil"></i></a>
                                        <a href="{% url 'manifiesto_app:completar-manifiesto' manifest.pk %}" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-thumbs-up"></i></a>
                                    </td>
                                  </tr>
                                {% endif %}
                            {% endif %}
                            {% empty %}
                                <td colspan="6">Lo sentimos no hay manifiestos a recepionar</td>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% else %}
    <h3>Necesita Permisos de Administrador</h3>
{% endif %}

{% endblock content_panel %}

nshipping/templates/manifiesto/manifest/report.html
{% extends "ingreso/nota_ingreso/base_nota.html" %}

{% block sidenav %}

    <li>
        <a class="active" href="{% url 'ingreso_app:nota-ingreso' %}"><i class="fa fa-fw fa-truck"></i> Nota De Ingreso</a>
    </li>
    <li>
        <a href="{% url 'ingreso_app:lista_envio' %}"><i class="fa fa-fw fa-paper-plane-o"></i> Entrega De Envios</a>
    </li>
    <li>
        <a href="{% url 'manifiesto_app:manifiesto-no-recepcionado' %}"><i class="fa fa-fw fa-cubes"></i> Recepcion de Paquetes</a>
    </li>
    <li>
        <a href="{% url 'salida_app:listar-egreso' %}"><i class="fa fa-fw fa-money"></i> Registro de Egresos</a>
    </li>

    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#caja">
            <i class="fa fa-fw fa-bullseye"></i>
            Caja Chica
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="caja" class="collapse">
            <li>
                <a href="{% url 'users_app:login-admin' user.pk %}">Cuadrar Caja</a>
            </li>
            <li>
                <a href="{% url 'salida_app:users-activos' %}">Consultar Agencias</a>
            </li>
        </ul>
    </li>

    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#manifiesto">
            <i class="fa fa-fw fa-bullseye"></i>
            Manifiesto
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="manifiesto" class="collapse">
            <li>
                <a href="{% url 'manifiesto_app:listar-manifiesto' %}">Manifiesto En Curso</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:agregar-manifiesto' %}">Manifiesto Empresa</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:agregar-sub_contrata' %}">Manifiesto por Sub-Contrata</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#mantenimiento">
            <i class="fa fa-fw fa-cogs"></i>
            Mantenimiento
            <i class="fa fa-fw fa-caret-down"></i>
        </a>
        <ul id="mantenimiento" class="collapse">
            <li>
                <a href="{% url 'ingreso_app:listar-branch' %}">Sucursales</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:listar-carro' %}">Vehiculos</a>
            </li>
            <li>
                <a href="{% url 'manifiesto_app:listar-conductor' %}">Conductores</a>
            </li>
        </ul>
    </li>

{% endblock sidenav %}

{% block content_panel %}

{% if user.is_superuser %}

    <div class="row">
        <div class="col-xs-12">
            <h3 class="page-header title-quilla">Sucursales que se Arribaran</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <table class="table table-bordered table-hover table-condensed table-quilla">
                <thead>
                    <tr>
                        <th>Nro Manifiesto</th>
                        <th>Conductor</th>
                        <th>Carro</th>
                        <th>Origen</th>
                        <th>Destino</th>
                        <th class="text-center">Acción</th>
                    </tr>
                </thead>
                <tbody>
                        {% for s in sucursales %}
                        <tr>
                            <td>{{object.pk}}</object></td>
                            <td>{{object.driver}}</td>
                            <td>{{object.car}}</td>
                            <td>{{object.origin}}</td>
                            <td>{{s.name}}</td>
                            <td>
                                <a href="{% url 'manifiesto_app:detalle-manifiesto' object.pk s.pk %}" class="btn btn-sm btn-success"><i class="fa fa-print fa-lg"></i></i>Imprimir</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% else %}
    <h3>Necesita Permisos de Administrador</h3>
{% endif %}
{% endblock content_panel %}